# NGC 1275 Configuration File

data:
  evfile : events.txt #our list of photon files
  scfile : /data/L1910170847288E15477E17_SC00.fits #our spacecraft file
  ltcube : null #generate a new ltcube (null) or add a path to an existing ltcube

binning:
  roiwidth   : 15.0 # Let's keep a small roi
  binsz      : 0.1 # bin size in degrees
  binsperdec : 8 # Ebins per decade in energy - 10 is a good estimate

selection:
  emin : 100  #our minimum energy
  emax : 300000  #our maximum energy
  zmax : 90  #our zenith angle
  evclass : 128  #our event class
  evtype : 3  #our event type
  tmin : 283996802  #our minimum time
  tmax : 315532802  #our maximum time
  filter : DATA_QUAL>0 && LAT_CONFIG==1 #A standard filter for gtmktime
  target : 'NGC 1275' # As NGC 1275 is in our 4FGL catalogue, we can simply type its name in, instead of the ra and dec of the source.

gtlike:
  edisp : True # Enable energy dispersion
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable  : ['isodiff', 'galdiff'] # Never enable energy dispersion for the isodiff or galdiff models

model:
  src_roiwidth : 20.0 #Includes sources outside of the ROI
  galdiff  : 'gll_iem_v07.fits' # The most recent and up to date model of the galactic diffuse emission
  isodiff  : 'iso_P8R3_SOURCE_V3_v1.txt' # The most recent and up to date model for the isotropic diffuse emission, and for our event class
  catalogs : ['4FGL-DR3'] # The 4FGL-DR3 catalogue, 12-year Fermi-LAT point source catalogue.
